name: culture-forward-api
region: nyc

services:
  - name: web
    environment_slug: node-js
    github:
      repo: myramade/nolavate
      branch: main
      deploy_on_push: true
    
    http_port: 5000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    build_command: npm run build
    run_command: npm start
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
    
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - name: db-mongodb-nyc3-18337
    engine: MONGODB
    production: true
